networks:
  dev:


services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80-80"
    volumes:
      - ./nginx/conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    networks:
      - dev

  frontend:
    build:
      context: ./templates
      dockerfile: Dockerfile
    networks:
      - dev