networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf.template:/etc/nginx/nginx.conf.template'
      - '/etc/letsencrypt:/etc/letsencrypt'
    environment:
      - SERVER_IP=${SERVER_IP}
    command: ["/bin/sh", "-c", "envsubst '${SERVER_IP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    

  backend:
    build:
      context: ./backend
    environment:
      - SERVER_IP=${SERVER_IP}
    networks:
      - dev

  frontend:
    build:
      context: ./frontend/todo-app
      args:
        - VITE_API_URL=http://${SERVER_IP}/api
    networks:
      - dev